sudo: false
language: python
python:
  - "2.7"
  - "3.5"
install:
  - "pip install flake8"
  - "pip install pytest"
  - "pip install pydocstyle"
  - "pip install tox-travis"
  - "pip install pylint"
script:
  - tox
  - pylint *.py modules/*.py
  - flake8 --exclude=./modules/__init__.py,modules/tests,.tox
  - pydocstyle *
